server:
  port: 4008
  servlet:
    context-path: /fresh-networks/fn-product
logging.level.io.swagger.models.parameters.AbstractSerializableParameter: ERROR
spring:
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 1000
  web:
    locale: ko_KR
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        connection:
          release_mode: on_close
        dialect:
          storage-engine: innodb
          format_sql: true
        show_sql: false
        format_sql: false
  datasource:
    hikari:
      maximumPoolSize: 10
      poolName: HikariCP
    url: ${SPRING_DATASOURCE_BASE_URL:jdbc:mysql://sfn-dev-01.ch624l3cypvt.ap-northeast-2.rds.amazonaws.com:3306}/fn_products?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: ${SPRING_DATASOURCE_BASE_USERNAME:root}
    password: ${SPRING_DATASOURCE_BASE_PASSWORD:1qaz1qaz}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

sfn:
  swagger:
    host: s-api-dev.smartfoodnet.com
    size:
      value: "페이지 크기 (default: ${spring.data.web.pageable.default-page-size})"
  service:
    fn-nosnos : http://localhost:8080/nosnos
    fn-warehouse-management-service : ${FN_WMS_BASE_URL:http://localhost:4001}/fresh-networks/fn-warehouse-service
