server:
  port: 4008
  servlet:
    context-path: /fresh-networks/fn-product
logging:
  slack:
    webhook-uri: ${SLACK_WEBHOOK_URI}
  config: classpath:logback-slack.xml
  level.io.swagger.models.parameters.AbstractSerializableParameter: ERROR
spring:
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 1000
  web:
    locale: ko_KR
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jpa:
    database-platform: com.smartfoodnet.config.querydsl.impl.Mysql8CustomDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          release_mode: on_close
        dialect:
          storage-engine: innodb
        show_sql: false
        format_sql: false
  datasource:
    hikari:
      maximumPoolSize: 10
      poolName: HikariCP
    url: ${SPRING_DATASOURCE_BASE_URL:jdbc:mysql://sfn-dev-01.ch624l3cypvt.ap-northeast-2.rds.amazonaws.com:3306}/fn_products?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: ${SPRING_DATASOURCE_BASE_USERNAME:root}
    password: ${SPRING_DATASOURCE_BASE_PASSWORD:1qaz1qaz}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

sfn:
  aws:
    region: ap-northeast-2
    sqs:
      endpoint: sqs.ap-northeast-2.amazonaws.com
    message: # SNS, SQS
      access-key: ${MESSAGE_ACCESS_KEY:uninitialized_message_access_key}
      secret-key: ${MESSAGE_SECRET_KEY:uninitialized_message_secret_key}
  async:
    poolSize: 10
  swagger:
    host: s-api-dev.smartfoodnet.com
    size:
      value: "페이지 크기 (default: ${spring.data.web.pageable.default-page-size})"
  service:
    code: FN-PRODUCT
    fn-message: ${FN_MESSAGE_SERVICE:http://fn-message.sfn-dev:4011/fresh-networks/fn-message}
    fn-warehouse-management-service: ${FN_WAREHOUSE_SERVICE:http://fn-warehouse-service.sfn-dev:4001/fresh-networks/fn-warehouse-service}
    fn-partner: ${FN_PARTNER_SERVICE:http://fn-partner-service.sfn-dev:4007/fresh-networks/fn-partner}

sqs:
  queues:
    fn-product:
      basic-product-created:
        name: ${SQS_BASIC_PRODUCT_CREATED_NAME:uninitialized}


feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 150
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
