server:
  port: 4008
  servlet:
    context-path: /fresh-networks/fn-product
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
spring:
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 1000
  web:
    locale: ko_KR
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          release_mode: on_close
        dialect:
          storage-engine: innodb
          format_sql: true
        show_sql: true
        format_sql: true
  datasource:
    hikari:
      maximumPoolSize: 10
      poolName: HikariCP
    url: ${SPRING_DATASOURCE_BASE_URL:jdbc:mysql://localhost:3306}/fn_products?useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    #    url: jdbc:mysql://localhost:3306/fn_products?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: ${SPRING_DATASOURCE_BASE_USERNAME:root}
    password: ${SPRING_DATASOURCE_BASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
sfn:
  aws:
    region: ap-northeast-2
    sqs:
      endpoint: sqs.ap-northeast-2.amazonaws.com
    message: # SNS, SQS
      access-key: ${MESSAGE_ACCESS_KEY:uninitialized_message_access_key}
      secret-key: ${MESSAGE_SECRET_KEY:uninitialized_message_secret_key}
  async:
    poolSize: 10
  swagger:
    host: localhost:4008
    size:
      value: "페이지 크기 (default: ${spring.data.web.pageable.default-page-size})"
  service:
    fn-message: ${FN_MESSAGE_BASE_URL:https://s-api-dev.smartfoodnet.com/fresh-networks/fn-message}
    fn-warehouse-management-service: ${FN_WMS_BASE_URL:http://localhost:4001}/fresh-networks/fn-warehouse-service


sqs:
  queues:
    fn-product:
      basic-product-created:
        name: ${SQS_BASIC_PRODUCT_CREATED_NAME:uninitialized}
